---
# https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/deployment-v1/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-work-app-backend  # リソース名 (名前空間内で一意でなければならない)
spec:
  replicas: 3
  selector:
    matchLabels:
      # このラベルと一致する spec.template.metadata.labels を持つ Pod がレプリカセットの対象となる
      app: eks-work-app-backend
  template:
    metadata:
      labels:
        app: eks-work-app-backend
    spec:
      containers:
      - name: eks-work-app-backend
        image: 674582907715.dkr.ecr.ap-northeast-1.amazonaws.com/eks-work-app/backend:latest
        ports:
        - containerPort: 8000

---
# https://kubernetes.io/docs/reference/kubernetes-api/service-resources/service-v1/
apiVersion: v1
kind: Service
metadata:
  name: backend-eks-work-app
spec:
  selector:
    # このセレクタにマッチするラベルキーと値を持つポッドにサービストラフィックをルーティングします。
    app: eks-work-app-backend
  ports:
  - port: 8000

---
# https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/deployment-v1/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-work-app-frontend  # リソース名 (名前空間内で一意でなければならない)
spec:
  replicas: 3
  selector:
    matchLabels:
      # このラベルと一致する spec.template.metadata.labels を持つ Pod がレプリカセットの対象となる
      app: eks-work-app-frontend
  template:
    metadata:
      labels:
        app: eks-work-app-frontend
    spec:
      containers:
      - name: eks-work-app-frontend
        image: 674582907715.dkr.ecr.ap-northeast-1.amazonaws.com/eks-work-app/frontend:latest
        ports:
        - containerPort: 3000

---
# https://kubernetes.io/docs/reference/kubernetes-api/service-resources/service-v1/
apiVersion: v1
kind: Service
metadata:
  name: frontend-eks-work-app
spec:
  selector:
    # このセレクタにマッチするラベルキーと値を持つポッドにサービストラフィックをルーティングします。
    app: eks-work-app-frontend
  ports:
  - port: 3000

---
# https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/deployment-v1/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-work-app-nginx  # リソース名 (名前空間内で一意でなければならない)
spec:
  replicas: 2
  selector:
    matchLabels:
      # このラベルと一致する spec.template.metadata.labels を持つ Pod がレプリカセットの対象となる
      app: eks-work-app-nginx
  template:
    metadata:
      labels:
        app: eks-work-app-nginx
    spec:
      containers:
      - name: eks-work-app-nginx
        image: 674582907715.dkr.ecr.ap-northeast-1.amazonaws.com/eks-work-app/nginx:latest
        ports:
        - containerPort: 80
#---
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: eks-work-app-  # リソース名 (名前空間内で一意でなければならない)
#spec:
#  replicas: 3
#  selector:
#    matchLabels:
#      
#      app: eks-work-app
#  template:
#    metadata:
#      labels:
#        # spec.selector.matchLabels
#        app: eks-work-app
#    spec:
#      containers:
#      - name: backend.eks-work-app.local
#        image: 674582907715.dkr.ecr.ap-northeast-1.amazonaws.com/eks-work-app/backend:latest
#        ports:
#        - containerPort: 8000
#        env:
#        - name: STAGE
#          value: prd
#      - name: frontend.eks-work-app.local
#        image: 674582907715.dkr.ecr.ap-northeast-1.amazonaws.com/eks-work-app/frontend:latest
#        ports:
#        - containerPort: 3000
#      - name: nginx.eks-work-app.local
#        image: 674582907715.dkr.ecr.ap-northeast-1.amazonaws.com/eks-work-app/nginx:latest
#        ports:
#        - containerPort: 80