---
version: '3.2'
services:
  backend:
    build:
      context: ./
      dockerfile: docker/backend/Dockerfile
    container_name: backend
    hostname: backend.eks-work-app.local
    volumes:
      - type: bind
        source: ${HOST_PROJECT_ROOT}/backend
        target: /opt/app
    command: /usr/local/bin/entrypoint.sh --debug
    environment:
      - STAGE=dev
    networks:
      br-eks-work-app: {}
  front:
    build:
      context: ./
      dockerfile: docker/frontend/Dockerfile
    container_name: frontend
    hostname: frontend.eks-work-app.local
    volumes:
      - type: bind
        source: ${HOST_PROJECT_ROOT}/frontend
        target: /opt/app
    entrypoint: /usr/local/bin/entrypoint.sh --debug
    networks:
      br-eks-work-app: {}
  nginx:
    build:
      context: ./
      dockerfile: docker/nginx/Dockerfile
    container_name: nginx
    hostname: nginx.eks-work-app.local
    networks:
      br-eks-work-app: {}
networks:
  br-eks-work-app:
    driver: bridge
    name: br-eks-work-app
    external: true