version: '3.2'
services:
  main:
    hostname: main.eks-work-app.local
    build:
      context: ../
      dockerfile: docker/devcontainer/Dockerfile
    volumes:  # docker-compose.yml があるディレクトリからの相対パスで指定する
      - ..:/eks-work-app:cached
      - ~/.aws:/home/vscode/.aws:cached
      - ~/.ssh:/home/vscode/.ssh:cached
      - ~/.docker:/home/vscode/.docker:cached
    command: sleep infinity
    networks:
      br-eks-work-app: {}

networks:
  br-eks-work-app:
    driver: bridge
    name: br-eks-work-app