# Kustomization File: https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/
# Kustomizeの概要と使い方: https://note.shiftinc.jp/n/nd7f17e51d592#ef1a28c4-390c-4359-9f2f-48134111fdd8
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  # baseのkustomization.yamlが存在するディレクトリの相対パスを指定
  - ../../base
# namespace: https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/namespace/
#   既存の名前空間がリソースに設定されている場合は上書き、リソースに設定されていない場合は追加
namespace: production

# replicas: https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/replicas/
# nameに一致するDeploymentやReplicaSetのレプリカ数を上書き
replicas:
- name: eks-work-app-backend
  count: 4
- name: eks-work-app-frontend
  count: 4
- name: eks-work-app-nginx
  count: 3

# images: https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/images/
# nameに一致するコンテナイメージのタグを上書き
images:
- name: 674582907715.dkr.ecr.ap-northeast-1.amazonaws.com/eks-work-app/backend
  newTag: latest
- name: 674582907715.dkr.ecr.ap-northeast-1.amazonaws.com/eks-work-app/frontend
  newTag: latest
- name: 674582907715.dkr.ecr.ap-northeast-1.amazonaws.com/eks-work-app/nginx
  newTag: latest
